version: "3.8"

services:
  bd:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: bd_clientes
    ports:
      - "14330:1433"  # Puerto externo cambiado a 14330
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=UPT.2024
    volumes:
      - ./db:/tmp

  api:
    build: .
    container_name: api_clientes
    image: clienteapi-api:latest
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__ClienteDB=Server=bd,1433;Database=BD_CLIENTES;User Id=sa;Password=UPT.2024;TrustServerCertificate=true
    depends_on:
      - bd

  sqlcmd:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlcmd_tool
    command: sleep infinity
    volumes:
      - ./db:/tmp
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

networks:
  default:
    driver: bridge