global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'apiCliente'
    scheme: http
    metrics_path: /health
    static_configs:
      - targets: ['api_clientes:80']

  - job_name: 'apiCliente_healthcheck'
    scheme: http
    metrics_path: /health
    static_configs:
      - targets: ['api_clientes:80']
